version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: consumos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./datasets:/app/datasets:delegated
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=consumos_db
      - DATA_FOLDER=datasets
      - BATCH_SIZE=1000
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "test -d /app/datasets && ls -la /app/datasets"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 